DROP TABLE IF EXISTS POLL_ANSWERS;
DROP TABLE IF EXISTS POLL_MODEL_ANSWERS;
DROP TABLE IF EXISTS POLL_QUESTIONS;

CREATE TABLE POLL_QUESTIONS
(
    question_id INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
    multiple_answers BOOLEAN NOT NULL,
    question VARCHAR(255) NOT NULL
);

CREATE TABLE POLL_MODEL_ANSWERS
(
    poll_model_question_id INTEGER NOT NULL,
    answers VARCHAR(200) NOT NULL,
    FOREIGN KEY (poll_model_question_id) REFERENCES POLL_QUESTIONS(question_id)
);

CREATE TABLE POLL_ANSWERS
(
    id INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
    question_id INTEGER NOT NULL,
    answer VARCHAR(200) NOT NULL,
    FOREIGN KEY (question_id) REFERENCES POLL_QUESTIONS(question_id)
);
